from array import *
arr=array('i',[100,200,300,400,500])
print("Original array: ",arr)
arr.append(600)
arr.append(700)
print("After adding: ",arr)
arr.insert(1,150)
print("After inserting: ",arr)
arr.remove(200)
print("After removing: ",arr)
arr.pop()
print("After pop: ",arr)
n=arr.index(300)
print("Index of 300 is: ",n)
mylist=arr.tolist()
print("List: ",mylist)
print("Array: ",arr)
