print("Queue using list")
queue=[]
queue.append(1)
queue.append("hi")
queue.append(45)
queue.append("welcome")
print("The queue is",queue)
a=queue.pop(0)
b=queue.pop(0)
print("The element deleted is",a)
print("The element deleted is",b)
print("The first element is",queue[0])
print("The queue after deleting: ",queue)
print("To find the queue is full or not")
print(len(queue)==0)

print("Queue using queue")
from queue import Queue
q=Queue(max==4)
q.put(2)
q.put(56)
q.put("hi")
q.put("Hello")
print(q.queue)
a=q.get()
print("The element deleted is",a)
print("The first element of the queue is",q.queue[0])
print("The queue after deletion is",q.queue)
print("The queue is empty or not")
print(q.empty())
print("The queue is full or not") 
print(q.full())
      
